spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/employee?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

javax:
  cache:
    cacheName: user,role
    maxHeap: 2000
    tti: 600


logging:
  level:
    root: info
  switch: spring

indi:
  pf:
    jwt:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

# yml 文件在IDEA中build不会复制到target文件中， 但是Maven compile 可以，考虑rebuild 项目以Maven project形式（Maven -> reimport）

# -----------------Spring Datasource 配置 -----------------------
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa
#    data: classpath:sql/data.sql
#    schema: classpath:sql/db_ddl.sql

# -----------------Spring ehcache 配置 -----------------------
#spring:
#  cache:
#    ehcache:
#      config: classpath:indi/mat/work/project/config/ehcache.xml
