
indi:
  enable: true
  orm: druid
  service-id: indi.mat.work.db
  service-aop : execution(* indi.mat.work.db.service.*.*(..))
  db:
    maxActive: 5
    initialSize: 1
    minIdle: 1
    maxWait: 3000
    hostName: localhost
    hostIp: 127.0.0.1
    hostPort: 3306
    instance: test
    dbType: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    dbName: test
    username: root
    password: 123456
